name = "RetinalTwin"
uuid = "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
authors = ["Matt Tarchick"]
version = "0.1.0"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
CairoMakie = "0.15.8"
DSP = "0.8.4"
DifferentialEquations = "7.17.0"
FFTW = "1.10.0"
GLMakie = "0.13.8"
LinearAlgebra = "1.11.0"
Parameters = "0.12.3"
Setfield = "1.1.2"
StaticArrays = "1.9.16"
Statistics = "1.11.1"
julia = "1.10"
